#%RAML 1.0
version: v1
title: sample-api


/employee:
  get:
    headers: 
      correlationId:
        type: string

    queryParameters: 
      id:
        type: string

    responses: 
      200:

  /{employeeID}:
    get:
      headers: 
        correlationId:
          type: string
      responses: 
        200:
    patch:
      headers: 
        correlationId:
          type: string
      body: 
        application/json:
          example: !include patch-example.json
          

